package com.libgdx.treasurehunter.utils


enum class GameObject() {
    CAPTAIN_CLOWN,
    CAPTAIN_CLOWN_SWORD,
    CRABBY,
    FIERCE_TOOTH,
    PINK_STAR,
    BACK_PALM_TREE_RIGHT,
    BACK_PALM_TREE_LEFT,
    BACK_PALM_TREE_REGULAR,
    FRONT_PALM_TREE,
    PALM_TREE_BOTTOM_RIGHT,
    PALM_TREE_BOTTOM_LEFT,
    PALM_TREE_BOTTOM_REGULAR,
    CHEST,
    FLAG,
    SHIP_HELM,
    DEAD_MARK,
    ATTACK_1,
    ATTACK_2,
    ATTACK_3,
    AIR_ATTACK_1,
    AIR_ATTACK_2,
    SWORD,
    ATTACK_EFFECT,
    SWORD_EMBEDDED,
    INTERROGATION_MARK,
    EXCLAMATION_MARK,
    SPIKES,
    DUST_PARTICLES,
    GROUND;
    val atlasKey = this.name.lowercase()
}
